import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from './../Components/Header';
import Banner from '@/Components/Banner';
import ProductFeed from '@/Components/ProductFeed';
import axios from 'axios';

const inter = Inter({ subsets: ['latin'] })

export default function Home({product}) {

  return (
    <div className='bg-gray-100'>
      <Head>
        <title>Amazon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/icon.png" />
      </Head>
      {/* Header */}
      <Header />

      <main className='max-w-screen-2xl mx-auto'>
        {/* banner */}
          <Banner />

        {/* product */}
        <ProductFeed product={product}/>
      </main>
    </div>
  )
}


export async function getServerSideProps(context) {

  let {data }= await axios.get("https://fakestoreapi.com/products");
  return {
    props: {
      product : data
    }, 
  }
}
